version: '3.5'
services:
  dreamerv3-ssbu:
    image: dreamerv3-ssbu:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dreamerv3-ssbu
    runtime: nvidia
    tty: true
    environment:
      - SERVER_ADDRESS=${SERVER_ADDRESS}
    volumes:
      - ${LOG_DIR}:/root/logdir
  tensorboard:
    image: tensorflow/tensorflow:latest
    container_name: dreamerv3-tensorboard
    ports:
      - ${TENSORBOARD_PORT}:6006
    volumes:
      - ${LOG_DIR}:/root/logdir
    command: tensorboard --logdir /root/logdir --bind_all