version: '3.5'
services:
  dreamerv3-ssbu:
    image: dreamerv3-ssbu:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dreamerv3-ssbu
    tty: true
    ports:
      - 8008:8008 # port for api
    environment:
      - SERVER_ADDRESS=http://192.168.207.236:8008
    volumes:
      - ./logdir:/root/logdir